### ISSUE TITLE
[Featurerequest] Generic io.Writer interfaces for every log interface

### ISSUE THREAD

**Issue by dragonchaser** [Masterminds/log-go#16]
It is a very common case to pass contents to an io.Writer.
In many cases one would just want this content to end up in your logs.
For example when one creates a cobra command you pass `os.Stdout` to the out parameter of the new command.
It would be very helpful to have access to each implemtations io.Writers like `impl/cli/cli.go` does 
(see https://github.com/mattfarina/log-go/blob/main/impl/cli/cli.go#L23-L43). 
For example for `impl/std/std.go` each of the structs field could point to `os.Stdout`.
As a result every logger would become more easy to replace by another implementation (which is not possible for us at the moment we have to stick to `impl/cli` for now (example: https://github.com/mattfarina/hypper/blob/viccuad/add-list/cmd/hypper/list.go#L74-L81).

**Comment by mattfarina** [comment]
There is a problem with exposing the io.Writer for each implementation. Some of the implementations do not make that accessible and do not have one easily accessible internally. If the Logger were to expose an io.Writer interface, which level should it be? Some might want info while others want Debug or Trace levels.

My solution can be found in the io package. Instead of exposing something internally, it makes any level accessible as an io.Writer. Even if the underlying implementation does not provide it.

Does that work?

**Comment by viccuad** [comment]
That would suffice, I'm consuming io for `hypper list` and `hypper install` succesfully. E.g: https://github.com/mattfarina/hypper/pull/37/commits/9d8878005e4d94409fc377d7bd44afbad59a6457
